/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_gui;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import library_access_api.*;

/**
 *
 * @author Max
 */
public class Book_SearchTable extends javax.swing.JFrame {
    
    static ArrayList<HomeSearch_Book_Data> _list;
    static String _resultString;
    
    /**
     * Creates new form Book_SearchTable
     */
    
    public Book_SearchTable(String resultString, ArrayList<HomeSearch_Book_Data> list) {
        _resultString = resultString;
        _list = list;
        
        initComponents();
                
        displayBookToJTable();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public static ArrayList<HomeSearch_Book_Data> get_Books_A_List() {
    	return _list;
    }
    
    public static String get_Search_String() {
    	return _resultString;
    }
        
    // added rows from arraylist to jtable
    public void displayBookToJTable()
    {
        DefaultTableModel model = (DefaultTableModel) book_results_jTable.getModel();
        Object rowData[] = new Object[4];
        for(int i = 0; i < _list.size(); i++)
        {
            rowData[0] = _list.get(i)._ISBN;
            rowData[1] = _list.get(i)._Title;
            rowData[2] = _list.get(i)._Authors;
            rowData[3] = _list.get(i)._Availability_Flag;
            model.addRow(rowData);
        }                
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_results_jScrollPane = new javax.swing.JScrollPane();
        book_results_jTable = new javax.swing.JTable();
        book_results_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        book_results_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author(s)", "Availability"
            }
        ));
        book_results_jScrollPane.setViewportView(book_results_jTable);

        book_results_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        book_results_jLabel.setText("Search Table with query: "+ get_Search_String());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book_results_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(book_results_jLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(book_results_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book_results_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_SearchTable(get_Search_String(),get_Books_A_List()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_results_jLabel;
    private javax.swing.JScrollPane book_results_jScrollPane;
    private javax.swing.JTable book_results_jTable;
    // End of variables declaration//GEN-END:variables
}
