/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_gui;

import java.sql.*;
import javax.swing.*;
import java.util.ArrayList;

import library_access_api.*;
/**
 *
 * @author Max
 */
public class HomeScreenSearchGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreenSearchGUI
     */
    public HomeScreenSearchGUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        check_outButton = new javax.swing.JButton();
        check_inButton = new javax.swing.JButton();
        input_borrowerButton = new javax.swing.JButton();
        resolve_finesButton = new javax.swing.JButton();
        update_finesButton = new javax.swing.JButton();
        library_titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        check_outButton.setText("CheckOut");
        check_outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_outButtonActionPerformed(evt);
            }
        });

        check_inButton.setText("CheckIn");
        check_inButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_inButtonActionPerformed(evt);
            }
        });

        input_borrowerButton.setText("InputBorrower");
        input_borrowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_borrowerButtonActionPerformed(evt);
            }
        });

        resolve_finesButton.setText("ResolveFines");
        resolve_finesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolve_finesButtonActionPerformed(evt);
            }
        });

        update_finesButton.setText("UpdateFines");
        update_finesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_finesButtonActionPerformed(evt);
            }
        });

        library_titleLabel.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        library_titleLabel.setText("SQL Library Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(check_outButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_inButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_borrowerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resolve_finesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_finesButton)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(library_titleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(library_titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_outButton)
                    .addComponent(check_inButton)
                    .addComponent(input_borrowerButton)
                    .addComponent(resolve_finesButton)
                    .addComponent(update_finesButton))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String searchStr = searchTextField.getText();		
       
        ArrayList<String> searchStr_ArrayList = new ArrayList<String>();
        
        String[] searchArray = searchStr.split("\\s+");
        
        for(String str : searchArray){
            searchStr_ArrayList.add(str);
        }
        
        ArrayList<HomeSearch_Book_Data> book;
        book = HomeSearchAPI.SearchBooks(searchStr_ArrayList);
		
        Book_SearchTable b_t = new Book_SearchTable(searchStr, book);
        b_t.setVisible(true);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void check_outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_outButtonActionPerformed
        CheckOutGUI c_o = new CheckOutGUI();
        c_o.setVisible(true);
    }//GEN-LAST:event_check_outButtonActionPerformed

    private void check_inButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_inButtonActionPerformed
        CheckInGUI c_i = new CheckInGUI();
        c_i.setVisible(true);
    }//GEN-LAST:event_check_inButtonActionPerformed

    private void input_borrowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_borrowerButtonActionPerformed
        InputBorrowerGUI ib = new InputBorrowerGUI();
        ib.setVisible(true);
    }//GEN-LAST:event_input_borrowerButtonActionPerformed

    private void update_finesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_finesButtonActionPerformed
        UpdateFinesAPI.UpdateFines_Done();
        JOptionPane.showMessageDialog(this, "All Fines Updated!");
    }//GEN-LAST:event_update_finesButtonActionPerformed

    private void resolve_finesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolve_finesButtonActionPerformed
        update_finesButtonActionPerformed(evt);
        
        ArrayList<ResolveFines_Data> borrower_fines;
        borrower_fines = ResolveFinesAPI.BorrowerFines_Data_Done();
		
        ResolveFines_Table f_t = new ResolveFines_Table(borrower_fines);
        f_t.setVisible(true);
    }//GEN-LAST:event_resolve_finesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreenSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreenSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreenSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreenSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreenSearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_inButton;
    private javax.swing.JButton check_outButton;
    private javax.swing.JButton input_borrowerButton;
    private javax.swing.JLabel library_titleLabel;
    private javax.swing.JButton resolve_finesButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton update_finesButton;
    // End of variables declaration//GEN-END:variables
}
