/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_gui;

import javax.swing.*;


import library_access_api.*;
/**
 *
 * @author Max
 */
public class InputBorrowerGUI extends javax.swing.JFrame {

    /**
     * Creates new form InputBorrowerGUI
     */
    public InputBorrowerGUI() {
        initComponents();
        
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promptNameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        promptSsnLabel = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        promptPNumberLabel = new javax.swing.JLabel();
        pnumberTextField = new javax.swing.JTextField();
        promptAddressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        RegisterBorrowerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        promptNameLabel.setText("Input Name");

        promptSsnLabel.setText("Input Ssn (xxx-xx-xxxx)");

        promptPNumberLabel.setText("Input Phone Number (opt.)");

        promptAddressLabel.setText("Input Address");

        RegisterBorrowerButton.setText("Register Borrower");
        RegisterBorrowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBorrowerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("(xxx) xxx-xxxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addressTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegisterBorrowerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(promptNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(promptSsnLabel)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(promptPNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel1))))
                            .addComponent(promptAddressLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {promptSsnLabel, ssnTextField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnumberTextField, promptPNumberLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promptPNumberLabel)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(promptSsnLabel)))
                    .addComponent(promptNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promptAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterBorrowerButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBorrowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBorrowerButtonActionPerformed
        String name_Str = nameTextField.getText();
        String ssn_Str = ssnTextField.getText();
        String pnumber_Str = pnumberTextField.getText();
        String address_Str = addressTextField.getText();
        
        boolean name_Str_flag = false;
        boolean ssn_Str_flag = false;
        boolean pnumber_Str_flag = false;
        boolean address_Str_flag = false;
        
        if(name_Str != null && !name_Str.isEmpty()){
            name_Str_flag = true;
        }
        
        if(ssn_Str != null && !ssn_Str.isEmpty()){
            ssn_Str_flag = true;
        }
        
        if(pnumber_Str != null && !pnumber_Str.isEmpty()){
            pnumber_Str_flag = true;
        }
        
        if(address_Str != null && !address_Str.isEmpty()){
            address_Str_flag = true;
        }
        
        //System.out.println("Condition name_Str_flag: " + name_Str_flag);
        //System.out.println("Condition ssn_Str_flag: " + ssn_Str_flag);
        //System.out.println("Condition address_Str_flag: " + address_Str_flag);
        
        if(name_Str_flag && ssn_Str_flag && address_Str_flag){
            boolean input_borrower_flag = InputBorrowerAPI.get_InputBorrower_Conditions(ssn_Str);
            
            if(input_borrower_flag == false){
                JOptionPane.showMessageDialog(this, "Conditions for InputBorrower not met", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                InputBorrowerAPI.CheckOut_Done(name_Str, ssn_Str, pnumber_Str, address_Str, pnumber_Str_flag);
                JOptionPane.showMessageDialog(this, "New borrower with name: " + name_Str + " has been registered.");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Name, Ssn, and Address are all required fields!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_RegisterBorrowerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputBorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputBorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputBorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputBorrowerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputBorrowerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterBorrowerButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pnumberTextField;
    private javax.swing.JLabel promptAddressLabel;
    private javax.swing.JLabel promptNameLabel;
    private javax.swing.JLabel promptPNumberLabel;
    private javax.swing.JLabel promptSsnLabel;
    private javax.swing.JTextField ssnTextField;
    // End of variables declaration//GEN-END:variables
}
