/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_gui;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import library_access_api.*;

/**
 *
 * @author Max
 */
public class Loan_SearchTable extends javax.swing.JFrame {
    
    static ArrayList<CheckInSearch_Loan_Data> _list;
    static String _resultString;
    
    /**
     * Creates new form Loan_SearchTable
     */
    
    public Loan_SearchTable(String resultString, ArrayList<CheckInSearch_Loan_Data> list) {
        _resultString = resultString;
        _list = list;
        
        initComponents();
        
        displayLoanToJTable();  
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public static ArrayList<CheckInSearch_Loan_Data> get_Loans_A_List() {
    	return _list;
    }
    
    public static String get_Search_String() {
    	return _resultString;
    }
    
    // added rows from arraylist to jtable
    public void displayLoanToJTable()
    {
        DefaultTableModel model = (DefaultTableModel) loan_results_jTable.getModel();
        Object rowData[] = new Object[7];
        for(int i = 0; i < _list.size(); i++)
        {
            rowData[0] = _list.get(i)._Bname;
            rowData[1] = _list.get(i)._LoanId;
            rowData[2] = _list.get(i)._ISBN;
            rowData[3] = _list.get(i)._CardId;
            rowData[4] = _list.get(i)._DateOut;
            rowData[5] = _list.get(i)._DueDate;
            rowData[6] = _list.get(i)._DateIn;        
            model.addRow(rowData);
        }                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loan_results_jScrollPane = new javax.swing.JScrollPane();
        loan_results_jTable = new javax.swing.JTable();
        loan_results_jLabel = new javax.swing.JLabel();
        promptLoanIdLabel = new javax.swing.JLabel();
        loanIdTextField = new javax.swing.JTextField();
        checkInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loan_results_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower Name", "Loan_Id", "ISBN", "Card_Id", "Date_Out", "Due_Date", "Date_In"
            }
        ));
        loan_results_jScrollPane.setViewportView(loan_results_jTable);

        loan_results_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loan_results_jLabel.setText("Search Table with query: "+ get_Search_String());

        promptLoanIdLabel.setText("Enter Loan Id:");

        checkInButton.setText("Check In");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loan_results_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loan_results_jLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(promptLoanIdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loanIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkInButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promptLoanIdLabel)
                    .addComponent(loanIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkInButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loan_results_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loan_results_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        String loanId_Str = loanIdTextField.getText();
        
        boolean check_in_flag = CheckInAPI.get_CheckIn_Conditions(loanId_Str);
        
        if (check_in_flag == false){
            JOptionPane.showMessageDialog(this, "Conditions for CheckIn not met", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            CheckInAPI.CheckOut_Done(loanId_Str);
            JOptionPane.showMessageDialog(this, "Loan with loan Id: " + loanId_Str + " checked in book");
        }
    }//GEN-LAST:event_checkInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan_SearchTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan_SearchTable(get_Search_String(),get_Loans_A_List()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInButton;
    private javax.swing.JTextField loanIdTextField;
    private javax.swing.JLabel loan_results_jLabel;
    private javax.swing.JScrollPane loan_results_jScrollPane;
    private javax.swing.JTable loan_results_jTable;
    private javax.swing.JLabel promptLoanIdLabel;
    // End of variables declaration//GEN-END:variables
}
