/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_gui;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import library_access_api.*;

/**
 *
 * @author Max
 */
public class ResolveFines_Table extends javax.swing.JFrame {
    
    static ArrayList<ResolveFines_Data> _list;
    
    /**
     * Creates new form ResolveFines_Table
     */
    public ResolveFines_Table(ArrayList<ResolveFines_Data> list) {
        _list = list;
        
        initComponents();
        
        displayFinesToJTable();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public static ArrayList<ResolveFines_Data> get_Fines_List() {
    	return _list;
    }
    
     public void displayFinesToJTable()
    {
        DefaultTableModel model = (DefaultTableModel) ResolveFinesTable.getModel();
        Object rowData[] = new Object[2];
        for(int i = 0; i < _list.size(); i++)
        {
            rowData[0] = _list.get(i)._Card_id;
            rowData[1] = _list.get(i)._SumFineAmt;
            model.addRow(rowData);
        }                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PromptCard_idLabel = new javax.swing.JLabel();
        Card_idTextField = new javax.swing.JTextField();
        ResolveFineCard_idButton = new javax.swing.JButton();
        ResolveFinesScrollPane = new javax.swing.JScrollPane();
        ResolveFinesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PromptCard_idLabel.setText("Enter Card ID number:");

        ResolveFineCard_idButton.setText("Resolve Fines");
        ResolveFineCard_idButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolveFineCard_idButtonActionPerformed(evt);
            }
        });

        ResolveFinesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Card_id", "Sum_Fines"
            }
        ));
        ResolveFinesScrollPane.setViewportView(ResolveFinesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResolveFinesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PromptCard_idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Card_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResolveFineCard_idButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PromptCard_idLabel)
                    .addComponent(Card_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResolveFineCard_idButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResolveFinesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResolveFineCard_idButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolveFineCard_idButtonActionPerformed
        String Card_Id_Str = Card_idTextField.getText();
        
        boolean resolveFineCard_flag = ResolveFinesAPI.get_ResolveFines_CardID_ExistsCondition(Card_Id_Str);
        
        if (resolveFineCard_flag == false){
            JOptionPane.showMessageDialog(this, "Conditions for resolving fines not met", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            ResolveFinesAPI.ResolveFines_Done(Card_Id_Str);
            JOptionPane.showMessageDialog(this, "Borrower with card Id: " + Card_Id_Str + " resolved all their fines.");
        }
    }//GEN-LAST:event_ResolveFineCard_idButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResolveFines_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResolveFines_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResolveFines_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResolveFines_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResolveFines_Table(get_Fines_List()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Card_idTextField;
    private javax.swing.JLabel PromptCard_idLabel;
    private javax.swing.JButton ResolveFineCard_idButton;
    private javax.swing.JScrollPane ResolveFinesScrollPane;
    private javax.swing.JTable ResolveFinesTable;
    // End of variables declaration//GEN-END:variables
}
